# Generated by Django 5.1.5 on 2025-05-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_firm', models.CharField(max_length=100, unique=True)),
                ('name_contact', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_family', models.CharField(blank=True, max_length=30)),
                ('name_first', models.CharField(max_length=30)),
                ('name_second', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('isPrj', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_staffrole', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prj', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('sum_prj', models.DecimalField(decimal_places=2, default=99999999.99, max_digits=12)),
                ('isDeleted', models.BooleanField(default=False)),
                ('contact_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prjcalendar.customer')),
                ('contact_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prjcalendar.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_prj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField()),
                ('date_work', models.DateField()),
                ('prjID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prjcalendar.project')),
                ('staffID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prjcalendar.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='roleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prjcalendar.staffrole'),
        ),
    ]
