# Generated by Django 5.1.5 on 2025-05-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prjcalendar', '0002_progress_project_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact_self',
        ),
    ]
