# Generated by Django 5.0.4 on 2025-09-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prjcalendar', '0003_remove_project_contact_self'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Права доступа')),
            ],
            options={
                'verbose_name': 'Группа пользователей',
                'verbose_name_plural': 'Группы пользователей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_projects', models.BooleanField(default=False, verbose_name='Просмотр проектов')),
                ('can_edit_projects', models.BooleanField(default=False, verbose_name='Редактирование проектов')),
                ('can_delete_projects', models.BooleanField(default=False, verbose_name='Удаление проектов')),
                ('can_view_staff', models.BooleanField(default=False, verbose_name='Просмотр сотрудников')),
                ('can_edit_staff', models.BooleanField(default=False, verbose_name='Редактирование сотрудников')),
                ('can_view_customers', models.BooleanField(default=False, verbose_name='Просмотр заказчиков')),
                ('can_edit_customers', models.BooleanField(default=False, verbose_name='Редактирование заказчиков')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Управление пользователями')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Просмотр отчетов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjcalendar.staff', verbose_name='Сотрудник')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjcalendar.usergroup', verbose_name='Группа пользователя')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Просмотр')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Редактирование')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Удаление')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_project_access', to=settings.AUTH_USER_MODEL, verbose_name='Предоставлено пользователем')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prjcalendar.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к проекту',
                'verbose_name_plural': 'Доступы к проектам',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
