# Generated by Django 5.0.4 on 2025-09-03 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjcalendar', '0004_usergroup_userprofile_projectaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('day', models.IntegerField(verbose_name='День месяца')),
                ('duration', models.IntegerField(default=1, verbose_name='Длительность (дни)')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prjcalendar.project', verbose_name='Проект')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prjcalendar.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['staff', 'day', 'created_at'],
                'unique_together': {('staff', 'day', 'project')},
            },
        ),
    ]
