# Generated by Django 5.0.4 on 2025-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjcalendar', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Цвет проекта'),
        ),
    ]
